language: smalltalk
sudo: true

branches:
  only:
    - master

os:
  - linux
  - osx
  - windows

smalltalk:
  - Pharo-7.0
  - Pharo64-7.0

before_install:
  - |
       # Otherwise build on OSX stucks at unknown fingerprint question
       echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
       
       declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/$GITHUB_SSH_FILE)"
       # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       openssl aes-256-cbc \
         -K $encrypted_269aad325b32_key \
         -iv $encrypted_269aad325b32_iv \
         -in ".travis/travis_id_rsa.enc" \
         -out "$SSH_FILE" -d

       # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

       # Enable SSH authentication

       chmod 600 "$SSH_FILE" \
         && printf "%s\n" \
              "Host github.com" \
              "  IdentityFile $SSH_FILE" \
              "  LogLevel ERROR" >> ~/.ssh/config

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
    fi
